#spring.application.name=Employees App
#spring.data.mongodb.uri= " ------------"
#spring.data.mongodb.database=employeedb
#spring.data.mongodb.auto-index-creation=true
#spring.main.allow-circular-references=true

#spring:
#  data:
#    mongodb:
#      uri:" ---------------- "
#      database: employeedb
#      auto-index-creation: true
#  main:
#    allow-circular-references: true


spring:
  profiles:
    active: Dev
server:
  port: 8080
  servlet:
    context-path: /Journal

