##spring.application.name=Employees App
##spring.data.mongodb.uri= " url of databse"
##spring.data.mongodb.auto-index-creation=true
##spring.main.allow-circular-references=true
#
spring:
  data:
    mongodb:
      uri:" usr of data base"
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true


