##spring.application.name=Employees App
##spring.data.mongodb.uri= " url of databse"
##spring.data.mongodb.database=employeedb
##spring.data.mongodb.auto-index-creation=true
##spring.main.allow-circular-references=true
#
spring:
  data:
    mongodb:
      uri: ---" url of database"
      database: journaldb
      auto-index-creation: true
  main:
    allow-circular-references: true


#server:
#  port: 8080
#  servlet:
#    context-path: /Journal



